name: Review and Approve Deployment

on:
  push:
    branches:
      - main

jobs:
  preview-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to day-2 and Set up Pulumi
        working-directory: ./day-2
        uses: pulumi/actions@v3
        with:
          stack-name: dev

      - name: Preview dev environment
        working-directory: ./day-2
        run: pulumi preview

  approve-dev:
    runs-on: ubuntu-latest
    needs: preview-dev
    steps:
      - name: Approval Gate
        run: echo "Waiting for approval to deploy dev environment"
        if: success() && github.event_name == 'workflow_dispatch'
    
  deploy-dev:
    runs-on: ubuntu-latest
    needs: approve-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Pulumi and deploy dev
        working-directory: ./day-2
        uses: pulumi/actions@v3
        with:
          stack-name: dev
          
      - name: Deploy dev environment
        working-directory: ./day-2
        run: pulumi up --yes

  preview-tst:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Preview tst environment
        working-directory: ./day-2
        uses: pulumi/actions@v3
        with:
          stack-name: tst
      - name: Preview tst environment
        working-directory: ./day-2
        run: pulumi preview

  approve-tst:
    runs-on: ubuntu-latest
    needs: preview-tst
    steps:
      - name: Approval Gate
        run: echo "Waiting for approval to deploy tst environment"
        if: success() && github.event_name == 'workflow_dispatch'

  deploy-tst:
    runs-on: ubuntu-latest
    needs: approve-tst
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy tst environment
        working-directory: ./day-2
        uses: pulumi/actions@v3
        with:
          stack-name: tst
      - name: Deploy tst environment
        working-directory: ./day-2
        run: pulumi up --yes
